import type { Context, Config } from "@netlify/edge-functions";

// ----------------------------------------------------------------------------
// Markdown for Agents — content negotiation on /
//
// Per the Cloudflare "Markdown for Agents" spec
// (https://developers.cloudflare.com/fundamentals/reference/markdown-for-agents/):
//
//   - Agent sends `Accept: text/markdown` to the same URL the browser uses.
//   - Server returns `Content-Type: text/markdown; charset=utf-8`
//     with `Vary: Accept`.
//   - Body is the page's content (non-content like nav/headers stripped),
//     with YAML frontmatter from meta tags and JSON-LD as fenced code.
//
// pawper.dev is a static site. Instead of converting HTML to Markdown at the
// edge (heavy, brittle), we serve a hand-curated Markdown homepage that
// mirrors the structure of /llms.txt — but in the per-URL negotiation shape
// the scanner expects. Browsers get the normal Astro HTML; agents get this.
// ----------------------------------------------------------------------------

const HOMEPAGE_MD = `---
title: "pawper.dev"
description: "Phillip A. Wessels' personal portfolio: projects pulled live from GitHub, long-form logs, a custom skills taxonomy, services, endorsements, and a resume. LCARS-themed Codex UI. Astro 6 + React 19, static, deployed to Netlify."
url: "https://pawper.dev"
author: "Phillip A. Wessels"
license: "Content (c) Phillip A. Wessels. Source code per repo licenses on GitHub."
---

# pawper.dev

> Personal portfolio and writing site for Phillip A. Wessels. Public, read-only, statically generated.

## What's here

- **Projects** — pulled from GitHub at build time (repos tagged \`portfolio-project\`), with language stats and a per-project commit history.
- **Logs** — long-form writing in Astro content collections, organized by series, kicker categories, and skills.
- **Skills** — custom taxonomy with distribution charts and per-skill filtering across projects and logs.
- **Services** — six service types (employment, contracting, consulting, coaching, speaking, mentoring) with endorsements pulled from Airtable.
- **Resume** — HTML resume at /resume.html; PDF generated by the build pipeline.

## Agent-discovery surfaces

These are the cleanest machine-readable entry points:

- [/llms.txt](https://pawper.dev/llms.txt) — full markdown sitemap of the site.
- [/.well-known/agent-card.json](https://pawper.dev/.well-known/agent-card.json) — A2A v1.0.0 agent card.
- [/.well-known/mcp.json](https://pawper.dev/.well-known/mcp.json) — MCP server card (advertises RSS as the read-only endpoints).
- [/.well-known/ai-agent.json](https://pawper.dev/.well-known/ai-agent.json) — Aiia manifest.
- [/.well-known/oauth-protected-resource](https://pawper.dev/.well-known/oauth-protected-resource) — RFC 9728 metadata; no auth (public read-only).
- [/sitemap.xml](https://pawper.dev/sitemap.xml) — full URL list.
- [/feed.xml](https://pawper.dev/feed.xml) — RSS feed of all logs.

## Navigation map

- \`/\` — home
- \`/about/\` — about Phillip and the site
- \`/projects/\` — all portfolio projects
- \`/logs/\` — all logs
- \`/services/\` — six service types with endorsements
- \`/contact/\` — contact info
- \`/agenda/\` — current focus and stated intentions
- \`/p/{id}/\` — individual project pages
- \`/l/{slug}/\` — individual log entries
- \`/skill/{id}/\` — per-skill page
- \`/resume.html\` — HTML resume

## How to read more

Fetch any URL with \`Accept: text/markdown\` to get the agent-readable form.
Fetch [/llms.txt](https://pawper.dev/llms.txt) for the complete site map.
`;

export default async (request: Request, _context: Context) => {
  const accept = (request.headers.get("accept") || "").toLowerCase();

  // Only intercept when the client explicitly prefers markdown. The default
  // browser Accept (`text/html,application/xhtml+xml,...`) does not list
  // text/markdown, so this is a no-op for human browsers.
  if (!accept.includes("text/markdown")) {
    return;
  }

  return new Response(HOMEPAGE_MD, {
    status: 200,
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "vary": "Accept",
      "cache-control": "public, max-age=300",
      "x-markdown-source": "edge-function",
    },
  });
};

export const config: Config = {
  path: "/",
};
